cdgriffith/FastFlix

- CHANGES
- fastflix/encoders/common/setting_panel.py
- fastflix/encoders/hevc_x265/command_builder.py
- fastflix/encoders/hevc_x265/settings_panel.py
- fastflix/flix.py
- fastflix/gui.py
- fastflix/version.py
- fastflix/widgets/command_runner.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/cover_panel.py
- fastflix/widgets/settings.py
- pyproject.toml
* Adding #83 HDR10+ support for x265 (thanks to SlashX)
* Adding x265 params hdr10, hdr10-opt, aq-mode and repeat-headers
* Adding basic splash info and waiting cursor for events
* Adding button to open config file from setting panel
* Changing that autocrop will test two spots if possible (thanks to HannesJo0139)
* Changing covers generated in their own temp directory
* Fixing #103 x265-params were being pre-pended with an extra ":" (thanks to Zeid164)
* Fixing #101 FFmpeg status codes now taken into account for errors
> Version 3.4.0

- CHANGES
- README.md
- fastflix/encoders/av1_aom/command_builder.py
- fastflix/encoders/hevc_x265/command_builder.py
- fastflix/encoders/rav1e/command_builder.py
- fastflix/encoders/svt_av1/command_builder.py
- fastflix/encoders/vp9/command_builder.py
- fastflix/encoders/vp9/settings_panel.py
- fastflix/flix.py
- fastflix/version.py
- pyproject.toml
* Fixing color space details being passed correctly to everything other than x265 as well
* Fixing HDR10+ details on README
* Fixing #102 better with taking into account master-display ratios (thanks to leonardyan)
* Fixing VP9 to accept profiles so HDR10 can be copied properly
* Fixing #108 HEVC can select wrong video track for encoding (thanks to Zeid164)
> Version  3.4.2

- fastflix/command_runner.py
- fastflix/conversion_worker.py
- fastflix/data/languages.yaml
- fastflix/shared.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/status_panel.py
Hi there! Thanks for making this software and all the blog posts. It's super great and has been super helpful to me!
I made this time elapsed label to keep track of how long the current encode command has been running.
Let me know if there are changes you'd like to see before merge 🙂
* Add `started_at` to `BackgroundRunner`
* Move `status_queue.put(("running",` to *after* `runner.start_exec` because start time of command is recorded in `start_exec`
* Add `timedelta_to_str` method for having a common serialization (it's quite hacky with only a string split to remove microseconds)
* Change separator for status update signals from `:` to `__` because ISO formatted timestamps have `:` in them which made it a little difficult to send it along with the other data
* Add a label for time elapsed …
> Add time elapsed to enoding status tab

- CHANGES
- fastflix/encoders/copy/settings_panel.py
- fastflix/models/config.py
- fastflix/version.py
- fastflix/widgets/panels/advanced_panel.py
* Fixing #156 Copy was broken due to copy settings being renamed due to library update (thanks to leonardyan)
* Fixing #172 FastFlix could not set profile setting copy (thanks to Etz)
* Fixing calling delete on a profile without a source video could crash FastFlix
> Version 4.1.1

- fastflix/program_downloads.py
#187 
Provides user with feedback that download has been canceled and deletes partial download file.
> Graceful cancel of FFmpeg download

- fastflix/encoders/common/setting_panel.py
I've run into this bug when testing the NVENC encoder the other day. The RC Lookahead is stored as int in yaml but the Qt widget expects a string.
> Cannot load NVENC profiles because RC Lookahead is stored as int

- CHANGES
- fastflix/shared.py
- fastflix/version.py
- fastflix/widgets/changes.py
* Fixing #264 changelog encoding was causing crashes on non utf-8 systems (thanks to lobofoot)
> Version 4.4.2

- CHANGES
- fastflix/widgets/panels/audio_panel.py
- fastflix/widgets/panels/status_panel.py
-psnr causes output of PSNR=Y:nan U:nan V:nan *:nan which breaks the current parser. Treat the = split differently.
Also 640k is a very standard and well supported audio bitrate. It is the max for AC3 and is a required bitrate for bluray. Add it and simplify the  channels not specified case (the old list was the same increment as channels=2).
> Fix parsing of output with -psnr on and add 640k audio bitrate

- CHANGES
- README.md
- fastflix/encoders/qsvencc_avc/command_builder.py
- fastflix/version.py
* Fixing QSV AVC command builder not working (thanks to Marco Ravich)
* Fixing missing details in readme on how to use additional encoders
> Version 4.9.1

- .github/workflows/build.yaml
- CHANGES
- fastflix/data/languages.yaml
- fastflix/encoders/vvc/command_builder.py
- fastflix/version.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/queue_panel.py
- pyproject.toml
* Fixing #431 Missing ubuntu 20 builds (thanks to techore)
* Fixing file extension drop down would not always set correct on encoder change (thanks to GT500org)
* Fixing missing translations for VVC
* Fixing VVC was adding extra params it did not support
* Fixing trying to restore a video from the queue that was using an encoder that no longer exists
> Version 5.2.2

- fastflix/data/languages.yaml
- fastflix/encoders/avc_x264/settings_panel.py
- fastflix/encoders/hevc_x265/settings_panel.py
- fastflix/encoders/vvc/settings_panel.py
- fastflix/language.py
- fastflix/widgets/settings.py
Absolutely love this program.
I've been using it for two years and it introduced me into the world of HDR, x265, and later av1.
Never found any translation issues before because I've been using the English version.
- Fixed some (not all) Chinese and Japanese translations
- Fixed a few typos "recommenced" --> "recommended"
- Changed the wording: "Slow is highest personal recommenced, as past that is much smaller gains" <-- the meaning of this sentence is not very clear, and some people may also find it "not gramatically correct".
- Changed the keys in the `language.yaml` to reflect the above change of strings.
- Added some single or double quotes to the `language.yaml`, as I found some strings to be at risk of misinterpretation
Disclaimer: I'm not a native speaker of English or Japanese, …
> Fixed some zho and jpn translations, fixed some typos

- CHANGES
- fastflix/encoders/av1_aom/command_builder.py
- fastflix/encoders/avc_x264/command_builder.py
- fastflix/encoders/common/helpers.py
- fastflix/encoders/copy/command_builder.py
- fastflix/encoders/ffmpeg_hevc_nvenc/command_builder.py
- fastflix/encoders/h264_videotoolbox/command_builder.py
- fastflix/encoders/hevc_videotoolbox/command_builder.py
- fastflix/encoders/hevc_x265/command_builder.py
- fastflix/encoders/rav1e/command_builder.py
- fastflix/encoders/svt_av1/command_builder.py
- fastflix/encoders/svt_av1_avif/command_builder.py
- fastflix/encoders/vaapi_h264/command_builder.py
- fastflix/encoders/vaapi_hevc/command_builder.py
- fastflix/encoders/vaapi_mpeg2/command_builder.py
- fastflix/encoders/vaapi_vp9/command_builder.py
- fastflix/encoders/vp9/command_builder.py
- fastflix/encoders/vvc/command_builder.py
- fastflix/encoders/webp/command_builder.py
- fastflix/version.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/queue_panel.py
- fastflix/widgets/settings.py
* Fixing #485 Cannot Restore Queue Containing HDR10+ Entries (thanks to Maddie Davis)
* Fixing #487 Filename corrupted on path change (thanks to Maddie Davis)
* Fixing #491 Can't open Setting in Chinese upgraded from old version (thanks to 谈天才)
* Fixing #493 Profiles did not load config for remove hdr, remove metadata or copy chapter toggles (thanks to micron888)
* Fixing #494 frame rate change in 2 pass mode ("Bitrate" mode) results in error for AVC x264 encoder (thanks to Ivan Gorin)
> Version 5.5.6

- fastflix/data/languages.yaml
- fastflix/widgets/settings.py
This Pull Request aim to fix several translation issues in GUI Portuguese language support, addressing the translation issues I mentioned here: #507
- Fixed all Portuguese strings mapped in the fastflix/data/languages.yaml file.
- Changed the string "Portuguese" to "Portuguese (Brazilian)" in fastflix/widgets/settings.py to accurately represent the language variant.
Despite the progress made in the translation, as mentioned in the issue ticket, there are yet a few outstanding issues require attention, since they affect other languages as well:
All the key fields from this window does exist in the YAML file and I have already translated each of them, but the fields aren't showing the correct mapped strings after changing the GUI language in the settings menu like the rest of the GUI.
The …
> Fix Portuguese translation issues

- CHANGES
- fastflix/encoders/common/audio.py
- fastflix/encoders/common/encc_helpers.py
- fastflix/encoders/common/setting_panel.py
- fastflix/version.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/abstract_list.py
- fastflix/widgets/panels/audio_panel.py
- fastflix/widgets/panels/subtitle_panel.py
- fastflix/widgets/windows/audio_conversion.py
- fastflix/widgets/windows/profile_window.py
* Fixing profile audio box not being able to select pattern match
* Fixing #561 Subtitles all show as English in FastFlix subtitles screen (thanks to David James)
* Fixing #562 Audio conversion window defaults channel layout to stereo (thanks to David James)
* Fixing #563 No Thumbnails When Importing Video (thanks to Damundai)
* Fixing #564 Audio custom bitrate box shows units in kilobits/second but passes bits/second as the parameter (thanks to tcmbackwards)
> Version 5.7.1

- pyproject.toml
I noticed when I did the Debian packages that themes style sheet aren't installed.
> Themes stylesheet aren't installed

- FastFlix.nsi
- fastflix/data/languages.yaml
@cdgriffith 
- Add Italian language
- Add info about inbstalelr exe file properteis
- Add info in Windows program list about program name, version, author and size
Change as you like author and copyright via these strings
!define PRODUCT_AUTHOR    "Chris Griffith"
!define PRODUCT_COPYRIGHT "(c) Chris Griffith 2021-2024"
Note if you run makensis via cmd line plwase check to run in this way
makensis /INPUTCHARSET UTF8 FastFlix.nsi
To ensure that the accenetd letetrs (like àèéòìù) are sued in right way,.
Thanks.
> Update NSIS installer script

- .github/workflows/build.yaml
- CHANGES
- FastFlix.nsi
- README.md
- fastflix/data/languages.yaml
- fastflix/encoders/nvencc_av1/command_builder.py
- fastflix/encoders/nvencc_avc/command_builder.py
- fastflix/encoders/nvencc_hevc/command_builder.py
- fastflix/encoders/qsvencc_av1/command_builder.py
- fastflix/encoders/qsvencc_avc/command_builder.py
- fastflix/encoders/qsvencc_hevc/command_builder.py
- fastflix/encoders/vceencc_av1/command_builder.py
- fastflix/encoders/vceencc_avc/command_builder.py
- fastflix/encoders/vceencc_hevc/command_builder.py
- fastflix/version.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/audio_panel.py
- fastflix/widgets/panels/subtitle_panel.py
- pyproject.toml
- scripts/build_mac_app.py
- scripts/get_version.py
* Fixing #598 'dict' object has no attribute 'to_yaml' (thanks to dmo marillat)
* Fixing #599 Italian language translations (thanks to bovirus)
* Fixing #600 Update NSIS installer script #601 to include Italian (thanks to bovirus)
* Fixing #603 Themes stylesheet aren't included in python package (thanks to dmo marillat)
* Fixing #605 HDR2SDR double tonemapping in Rigaya NVENC and QSV Encoders (thanks to Darksyderz)
> Version 5.8.1

- CHANGES
- fastflix/conversion_worker.py
- fastflix/encoders/hevc_x265/command_builder.py
- fastflix/entry.py
- fastflix/flix.py
- fastflix/language.py
- fastflix/models/config.py
- fastflix/models/fastflix.py
- fastflix/program_downloads.py
- fastflix/shared.py
- fastflix/version.py
- fastflix/widgets/container.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/queue_panel.py
- fastflix/widgets/settings.py
- fastflix/widgets/windows/audio_conversion.py
- fastflix/widgets/windows/profile_window.py
- pyproject.toml
* Adding global disable interlace check (thanks to Hexenhammer)
* Changing profile bitrate selector to be text field (thanks to Hexenhammer)
* Fixing #637 saving temp files for seven days to allow for better debug and recovery (thanks to marillat)
* Fixing #638 switching archived library appdirs to maintained platformdirs (thanks to marillat)
* Fixing x265 passlog file name was not being applied properly
* Fixing audio conversion list for rigaya encoders (thanks to Hexenhammer)
> Version 5.10.0

- fastflix/shared.py
Fixes a spelling error in a debug log in `latest_fastflix()`.
> fastflix/shared.py: Fix typo: "tp" → "to"

- CHANGES
- fastflix/data/languages.yaml
- fastflix/encoders/modify/command_builder.py
- fastflix/encoders/modify/settings_panel.py
- fastflix/ff_queue.py
- fastflix/version.py
- fastflix/widgets/background_tasks.py
- fastflix/widgets/panels/audio_panel.py
- fastflix/widgets/panels/cover_panel.py
- fastflix/widgets/panels/subtitle_panel.py
- fastflix/widgets/settings.py
- fastflix/widgets/windows/concat.py
- fastflix/widgets/windows/multiple_files.py
* Fixing #675 "Default Source Folder" not used when adding Complete Folders (thanks to Krawk)
* Fixing #678 Cannot copy the cover (thanks to danielly2020)
* Fixing #679 Subtitle extraction (thanks to danielly2020)
* Fixing adding subtitle track would fail if video has a title (thanks to The_Donn)
> Version 5.12.4
