- CHANGES
- flix/flix.py
- flix/version.py
* Fixing parse_hdr_details bug (thanks to Jan Temešinko and schlotkins)
Fixes issue #30 
(hopefully)
> Version 2.1.1

- CHANGES
- flix/flix.py
- flix/plugins/hevc/command_builder.py
- flix/plugins/hevc/settings_panel.py
- flix/version.py
* Adding custom extra ffmpeg args for HEVC
* Adding max mux queue size change for HEVC
* Fixing issue with codec not being set as copy (thanks to schlotkins)
* Fixing quotes around parens on linux
> Version 2.2.0

- CHANGES
- fastflix/plugins/av1/command_builder.py
- fastflix/plugins/av1/settings_panel.py
- fastflix/plugins/hevc/command_builder.py
- fastflix/plugins/hevc/settings_panel.py
- fastflix/plugins/svt_av1/settings_panel.py
- fastflix/plugins/vp9/command_builder.py
- fastflix/plugins/vp9/settings_panel.py
- fastflix/version.py
- pyproject.toml
* Fixing #39 HEVC two pass bitrate does not work (thanks to schlotkins)
> Version 2.3.2

- CHANGES
- fastflix/plugins/hevc/settings_panel.py
- pyproject.toml
* Fixing HEVC custom CRF issue
> Version 2.4.1

- .pre-commit-config.yaml
- CHANGES
- appveyor.yml
- fastflix/gui.py
- fastflix/plugins/av1/settings_panel.py
- fastflix/plugins/common/audio.py
- fastflix/plugins/gif/settings_panel.py
- fastflix/plugins/svt_av1/settings_panel.py
- fastflix/plugins/vp9/settings_panel.py
- fastflix/shared.py
- fastflix/version.py
- fastflix/widgets/about.py
- fastflix/widgets/container.py
- fastflix/widgets/logs.py
- fastflix/widgets/panels/audio_panel.py
- fastflix/widgets/settings.py
- pyproject.toml
- requirements-build.txt
* Adding settings dialog
* Fixing no bitrate should be specified for lossless audio
> Version 2.5.0

- CHANGES
- fastflix/plugins/gif/settings_panel.py
- fastflix/plugins/hevc_x265/settings_panel.py
- fastflix/plugins/vp9/settings_panel.py
- fastflix/version.py
- pyproject.toml
* Adding HEVC crf suggestions back
* Fixing #62 VP9 and GIF crashing due to label bug (thanks to -L0Lock-)
> Version 2.6.1

- CHANGES
- fastflix/gui.py
- fastflix/version.py
- pyproject.toml
* Switching windows builds from zeranoe.com to gyan.dev
> Version 2.6.2

- CHANGES
- fastflix/gui.py
- fastflix/plugins/svt_av1/command_builder.py
- fastflix/version.py
- fastflix/widgets/command_runner.py
- pyproject.toml
* Fixing #71 #26 encoding issues in video files (thanks to -L0Lock-)
* Fixing tempfile issue with recursion on cleanup
* Fixing SVT AV1 command building raising errors on bad crop
> Version 2.6.3

- CHANGES
- fastflix/gui.py
- fastflix/version.py
- fastflix/widgets/main.py
- pyproject.toml
* Fixing #76 Windows FFmpeg builds switch from gyan.dev to https://github.com/BtbN/FFmpeg-Builds/releases (thanks to sioc)
* Fixing failure size calculation limit on file to 500 bytes due to VP9
> Version  3.0.2

- CHANGES
- README.md
- fastflix/encoders/av1_aom/command_builder.py
- fastflix/encoders/avc_x264/command_builder.py
- fastflix/encoders/common/helpers.py
- fastflix/encoders/common/subtitles.py
- fastflix/encoders/gif/command_builder.py
- fastflix/encoders/hevc_x265/command_builder.py
- fastflix/encoders/rav1e/command_builder.py
- fastflix/encoders/svt_av1/command_builder.py
- fastflix/encoders/vp9/command_builder.py
- fastflix/flix.py
- fastflix/gui.py
- fastflix/shared.py
- fastflix/version.py
- fastflix/widgets/changes.py
- fastflix/widgets/command_runner.py
- fastflix/widgets/container.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/audio_panel.py
- fastflix/widgets/panels/subtitle_panel.py
- pyproject.toml
- requirements-build.txt
- requirements.txt
* Adding #75 burn-in subtitle support (thanks to Trevbams)
* Adding #81 auto crop feature (thanks to HannesJo0139)
* Adding #84 pause / resume functionality (thanks to loungebob)
* Adding hover info for Audio and Subtitle tracks
* Adding confirm overwrite dialog if file already exists and is not empty
* Adding linking to issues in changelog file
* Changing to explicitly set no-slow-firstpass for x265 bitrate runs
* Changing FFmpeg to download latest available
* Fixing AVC always copied chapters
* Fixing how aspect ratio interacted with crop
* Fixing HEVC would copy HDR10 details on 8-bit videos
> Version 3.2.0

- CHANGES
- fastflix/version.py
- pyproject.toml
* Fixing psutil not listed as requirement for pip (thanks to I-Iawk)
`pip` only release
> Version 3.2.1

- CHANGES
- fastflix/version.py
- fastflix/widgets/command_runner.py
- fastflix/widgets/main.py
- pyproject.toml
* Fixing #96 input selection did not support all video formats
* Fixing #95 unicode decode error for FFmpeg output
> Version  3.3.1

- CHANGES
- fastflix/encoders/common/setting_panel.py
- fastflix/encoders/hevc_x265/command_builder.py
- fastflix/encoders/hevc_x265/settings_panel.py
- fastflix/flix.py
- fastflix/version.py
- fastflix/widgets/main.py
- pyproject.toml
* Fixing #102 color space and HDR details not parsed from webm correctly (thanks to leonardyan)
* Fixing no warning messages for HDR10+ experimental feature
> Version 3.4.1

- CHANGES
- fastflix/encoders/hevc_x265/settings_panel.py
- fastflix/flix.py
- fastflix/gui.py
- fastflix/version.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/subtitle_panel.py
- fastflix/widgets/settings.py
- pyproject.toml
* Fixing #110 (multi) no warning for those updating about automatic burn-in subtitles (thanks to loungebob)
* Fixing #110 (multi) no option to disable automatic subtitle burn-in behavior  (thanks to loungebob)
* Fixing #110 (multi) waiting cursor may not go away by removing for now (thanks to loungebob)
* Fixing timeout for covers extraction not working
* Fixing changing settings without video would crash GUI
> Version 3.4.3

- CHANGES
- fastflix/encoders/av1_aom/command_builder.py
- fastflix/encoders/av1_aom/settings_panel.py
- fastflix/encoders/avc_x264/command_builder.py
- fastflix/encoders/avc_x264/settings_panel.py
- fastflix/encoders/common/helpers.py
- fastflix/encoders/common/setting_panel.py
- fastflix/encoders/copy/command_builder.py
- fastflix/encoders/copy/settings_panel.py
- fastflix/encoders/gif/command_builder.py
- fastflix/encoders/gif/settings_panel.py
- fastflix/encoders/hevc_x265/command_builder.py
- fastflix/encoders/hevc_x265/settings_panel.py
- fastflix/encoders/rav1e/command_builder.py
- fastflix/encoders/rav1e/settings_panel.py
- fastflix/encoders/svt_av1/command_builder.py
- fastflix/encoders/svt_av1/settings_panel.py
- fastflix/encoders/vp9/command_builder.py
- fastflix/encoders/vp9/settings_panel.py
- fastflix/encoders/webp/command_builder.py
- fastflix/encoders/webp/settings_panel.py
- fastflix/models/encode.py
- fastflix/version.py
- fastflix/widgets/container.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/status_panel.py
- fastflix/widgets/panels/subtitle_panel.py
- fastflix/widgets/video_options.py
* Adding dual pass option for ffmpeg options (thanks to Catatau)
* Fixing #120 custom bitrate forgets to add a "k" (thanks to seighail3)
* Fixing #162 Main window was not resizeable (thanks to bmcassagne)
> Beta Version 4.1.0b1

- CHANGES
- fastflix/encoders/copy/settings_panel.py
- fastflix/models/config.py
- fastflix/version.py
- fastflix/widgets/panels/advanced_panel.py
* Fixing #156 Copy was broken due to copy settings being renamed due to library update (thanks to leonardyan)
* Fixing #172 FastFlix could not set profile setting copy (thanks to Etz)
> Beta Version 4.1.1b0

- CHANGES
- fastflix/data/languages.yaml
- fastflix/encoders/common/setting_panel.py
- fastflix/encoders/svt_av1/settings_panel.py
- fastflix/shared.py
- fastflix/version.py
* Fixing #180 Minor UI glitch, custom bitrate retains "k" when edited from queue (thanks to Etz)
* Fixing custom QP crashes FastFlix (thanks to J-mas)
* Fixing adding a dot for microseconds in time fields would crash FastFlix (thanks to remlap)
* Fixing Chinese translations (thanks to leonardyan)
> Version 4.1.2

- fastflix/data/languages.yaml
I went through all of the German translation and fixed it to be more common language and having exact technical translation
> Fixed German translation

- fastflix/data/languages.yaml
- fastflix/widgets/settings.py
Long time no see! Also, in the settings/preferences panel, would you like to change the "Chinese" in language selection into "Chinese (simplified)"? Since I think there might be a traditional Chinese translation one day ;)
> Modify languages.yaml to adjust and fix some Chinese translation

- CHANGES
- fastflix/encoders/hevc_x265/command_builder.py
- fastflix/version.py
* Fixing colorspace details from advanced page not applied to x265 (thanks to Tình Em Là Đại Dương)
> Version 4.4.1

- CHANGES
- fastflix/encoders/vp9/command_builder.py
- fastflix/version.py
* Fixing #273 Realtime VP9 bitrate mode must be single pass (thanks to Owen Quinlan)
> Version 4.5.1

- CHANGES
- fastflix/conversion_worker.py
- fastflix/version.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/queue_panel.py
- fastflix/windows_tools.py
* Fixing #334 machine now sleeps during encoding (thanks to Don Gafford)
* Fixing After Conversion command running after every encoding (thanks to Don Gafford)
> Version 4.9.2

- .github/workflows/test.yaml
- CHANGES
- fastflix/version.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/queue_panel.py
* Fixing #339 After cancelling queue button stay as cancel (thanks to wynterca)
* Fixing internal error that after_done_action could not be set
> Verion 4.9.3

- CHANGES
- fastflix/data/languages.yaml
- fastflix/encoders/h264_videotoolbox/main.py
- fastflix/encoders/hevc_videotoolbox/main.py
- fastflix/flix.py
- fastflix/version.py
- fastflix/widgets/windows/concat.py
* Fixing Apple videotoolbox were not being listed as options (thanks to sublimal)
* Fixing concatenation of large amount of files could cause huge slowdowns to the app
* Fixing thumbnails command did not work when ffmpeg was in a directory with a space in it's lineage (thanks to No Name)
> Version 4.9.4

- fastflix/data/languages.yaml
Hey I'm back. I'm not an expert in video encoding and don't have enough time to do further investigation so simply fixed several apparent grammar problems.
> More Chinese translation fixes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CHANGES
- fastflix/entry.py
- fastflix/models/config.py
- fastflix/version.py
- fastflix/widgets/main.py
- pyproject.toml
* Fixing #426 Version 5.2 does not run on fresh install (thanks to Bandid0)
* Fixing #427 Error loading videos that do not have tags (thanks to Maddie Davis)
> Version 5.2.1

- CHANGES
- fastflix/ff_queue.py
- fastflix/version.py
- fastflix/widgets/panels/queue_panel.py
- pyproject.toml
* Fixing #433 queue_extras emptied on loading queue (thanks to Maddie Davis)
> Version 5.2.3

- CHANGES
- fastflix/data/languages.yaml
- fastflix/encoders/qsvencc_avc/settings_panel.py
- fastflix/encoders/qsvencc_hevc/settings_panel.py
- fastflix/encoders/svt_av1_avif/command_builder.py
- fastflix/encoders/svt_av1_avif/main.py
- fastflix/version.py
- fastflix/widgets/container.py
- fastflix/widgets/windows/multiple_files.py
- pyproject.toml
* Adding profile select in Load Directory window
* Adding `avis` and `avifs` extensions for AV1 (thanks to u/zimmwisdom)
* Fixing #439 QSVEnc QP mode select did not work in AVC / HEVC (thanks to sun6560032)
* Fixing current profile window would not show
> Version 5.3.0

- CHANGES
- README.md
- fastflix/data/languages.yaml
- fastflix/version.py
- fastflix/widgets/container.py
- fastflix/widgets/windows/profile_window.py
* Fixing #465 Russian translation (thanks to Ta0ba0)
* Fixing #466 AudioProfile could be deleted before fully created, causing runtime error (thanks to Jean-François Roy)
* Fixing to only allow one new profile window at a time
> Version 5.5.1

- .github/workflows/pythonpublish.yml
- CHANGES
- README.md
- fastflix/data/languages.yaml
- fastflix/encoders/common/helpers.py
- fastflix/version.py
- fastflix/widgets/main.py
- fastflix/widgets/windows/large_preview.py
* Adding #469 Romanian translations (thanks to RoDanny2021)
* Fixing #468 Custom resolutions not applying (thanks to GT500org)
> Version 5.5.2

- .github/workflows/pythonpublish.yml
- CHANGES
- fastflix/data/languages.yaml
- fastflix/language.py
- fastflix/version.py
- fastflix/widgets/settings.py
* Fixing missing language options (thanks to RoDanny2021)
> Version 5.5.3

- CHANGES
- fastflix/data/languages.yaml
- fastflix/encoders/common/setting_panel.py
- fastflix/encoders/nvencc_av1/command_builder.py
- fastflix/encoders/nvencc_av1/settings_panel.py
- fastflix/encoders/nvencc_avc/settings_panel.py
- fastflix/encoders/nvencc_hevc/command_builder.py
- fastflix/encoders/nvencc_hevc/settings_panel.py
- fastflix/encoders/qsvencc_av1/command_builder.py
- fastflix/encoders/qsvencc_av1/settings_panel.py
- fastflix/encoders/qsvencc_hevc/command_builder.py
- fastflix/encoders/qsvencc_hevc/settings_panel.py
- fastflix/encoders/svt_av1/settings_panel.py
- fastflix/encoders/vceencc_av1/command_builder.py
- fastflix/encoders/vceencc_av1/settings_panel.py
- fastflix/encoders/vceencc_hevc/command_builder.py
- fastflix/encoders/vceencc_hevc/settings_panel.py
- fastflix/models/encode.py
- fastflix/version.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/queue_panel.py
* Fixing #474 SVT-AV1 single pass would not be set on return from queue (thanks to veldspar)
* Fixing #475 Autocrop can break with index error (thanks to No Name / phanluchoaofficial1152)
* Fixing #477 HDR10+ not extracting with NVEncC encoder, switching to built in copy ability (thanks to Genine-Collin)
> Version 5.5.4

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- CHANGES
- fastflix/application.py
- fastflix/command_runner.py
- fastflix/data/languages.yaml
- fastflix/encoders/common/setting_panel.py
- fastflix/encoders/svt_av1/command_builder.py
- fastflix/encoders/svt_av1/settings_panel.py
- fastflix/ff_queue.py
- fastflix/models/video.py
- fastflix/shared.py
- fastflix/version.py
- fastflix/widgets/about.py
- fastflix/widgets/container.py
- fastflix/widgets/main.py
- fastflix/widgets/panels/abstract_list.py
- fastflix/widgets/panels/advanced_panel.py
- fastflix/widgets/panels/audio_panel.py
- fastflix/widgets/panels/debug_panel.py
- fastflix/widgets/panels/queue_panel.py
- fastflix/widgets/panels/subtitle_panel.py
- fastflix/widgets/settings.py
- fastflix/widgets/video_options.py
- fastflix/widgets/windows/disposition.py
- fastflix/widgets/windows/multiple_files.py
* Fixing #503 missing CRF mode for SVT-AV1 (thanks to ignace72)
* Fixing #506 excessive amounts of RAM used and not cleared - partially mitigated (thanks to 19Battlestar65)
* Fixing #509 Portuguese translations (thanks to Felipe Augusto Arantes de Souza)
* Fixing #513 Profile configuration issues, including with load directory (thanks to Nikita S.)
* Fixing #516 Performance improvements due to constant stream reads (thanks to William Barath)
> Version 5.5.7

- CHANGES
- fastflix/application.py
- fastflix/data/languages.yaml
- fastflix/encoders/avc_x264/command_builder.py
- fastflix/encoders/avc_x264/settings_panel.py
- fastflix/encoders/common/setting_panel.py
- fastflix/encoders/hevc_x265/command_builder.py
- fastflix/encoders/hevc_x265/settings_panel.py
- fastflix/encoders/vvc/command_builder.py
- fastflix/models/encode.py
- fastflix/shared.py
- fastflix/version.py
- fastflix/widgets/main.py
* Adding Passes option for bitrate mode in x265 and x264 (thanks to Chriss)
* Fixing VVC encode options (thanks to Chriss)
* Fixing #532 Trying to crop spams crop error (gendalv)
* Removing distutils in favor of packaging
* Removing #525 invalid 12 bit options for x264 (thanks to Chriss)
* Removing #497 #519 advanced checks for hardware encoders, due to them not always being detected (thanks to CptnFluffy)
> Version 5.6.0

- .github/workflows/build.yaml
- CHANGES
- fastflix/encoders/common/audio.py
- fastflix/encoders/common/encc_helpers.py
- fastflix/ff_queue.py
- fastflix/version.py
- fastflix/widgets/panels/audio_panel.py
* Fixing audio quality targeting to be enabled properly for ffmpeg
* Fixing #570 Changing audio language does not work (thanks to danielly2020)
* Fixing Setting audio track title does not work (thanks to Horatio on Discord)
* Fixing #571 AttributeError: 'NoneType' object has no attribute 'lower' (thanks to 'Dude' mikeSGman)
> Version 5.7.2

- CHANGES
- fastflix/data/languages.yaml
- fastflix/encoders/common/audio.py
- fastflix/shared.py
- fastflix/version.py
- fastflix/widgets/panels/queue_panel.py
* Fixing #574 Downmix audio channels not working (thanks to eikixsh)
* Fixing audio and subtitle track count in queue
> Version 5.7.3

- .github/workflows/build.yaml
- CHANGES
- fastflix/encoders/common/audio.py
- fastflix/encoders/common/encc_helpers.py
- fastflix/flix.py
- fastflix/models/encode.py
- fastflix/version.py
- fastflix/widgets/background_tasks.py
- fastflix/widgets/panels/subtitle_panel.py
- fastflix/widgets/windows/hdr10plus_inject.py
- fastflix/widgets/windows/profile_window.py
* Fixing #578 Missing code signing to FastFlix exec inside of the installer (thanks to Sam Katakouzinos)
* Fixing #579 Missing Infos and no Mouse-Over info in Subs-Panel since 5.7 (thanks to GeZorTenPlotZ)
* Fixing #580 No Downmix key error on profile save (thanks to Hankuu)
* Fixing #581 Fastflix could not recognize hevc video containing hdr10plus metadata with recent ffmpeg build (thanks to alpha-0)
> Version 5.7.4

- fastflix/data/languages.yaml
@cdgriffith 
Please merge. Thanks.
> Update Italian language

- fastflix/encoders/vvc/command_builder.py
Correct command line option for IDC level for VVenC from -levelidc to -level
> [fix] replace correct cmd line option for IDC level

- fastflix/__main__.py
- fastflix/models/config.py
- fastflix/widgets/changes.py
> Fix various typos

- fastflix/encoders/common/setting_panel.py
```diff
- the resolution-to-CRFare mere suggestions!
+ the resolution-to-CRF are mere suggestions!
```
> Add missing space to CRF tooltip

- CHANGES
- fastflix/data/languages.yaml
- fastflix/version.py
- fastflix/widgets/background_tasks.py
- fastflix/widgets/panels/subtitle_panel.py
- fastflix/widgets/video_options.py
* Fixing #673 changing subtitle language in the UI did not take effect in the command (thanks to danielly2020)
* Fixing #673 extract subtitle command was looking for subtitle index, not absolute index (thanks to danielly2020)
> Version 5.12.3

- CHANGES
> CHANGES: fix typo
